Repository CDCgov/sirfunctions, pull requests merged in 2024-10, with the labels that each got.

#135 ❇️ Expand use of `f.npafp.rate.01()` and `f.stool.ad.01()` for use in multiple countries
  NAMESPACE
  R/f.npafp.rate.01.R
  R/f.npafp.rate.02.R
  R/f.stool.ad.01.R
  man/f.npafp.rate.02.Rd
  man/npafp_rolling.Rd
  man/npafp_year.Rd
Labels: bug, enhancement

#136 127 add ability to write png files to edav io
  R/dal.R
Labels: enhancement

#138 137 add spatial dev option to load clean spatials
  R/dal.R
Labels: enhancement

#146 ❇️ add flexibility to core functions
  R/f.npafp.rate.01.R
  man/npafp_rolling.Rd
  man/npafp_year.Rd
Labels: enhancement

#148 update pos dupe check, closes #147
  R/dal.R
Labels: bug

#159 🐛 Add age filter in f.npafp.rate.01 and weight column in year table
  NAMESPACE
  R/f.npafp.rate.01.R
  R/f.stool.ad.01.R
  man/edav_io.Rd
  man/load_clean_ctry_sp.Rd
  man/load_clean_dist_sp.Rd
  man/load_clean_prov_sp.Rd
Labels: bug, High Priority

#157 ❇️ Desk review mapping functions now use long spatial data
  R/dr.figure.functions.R
  man/generate_afp_case_map.Rd
  man/generate_es_det_map.Rd
  man/generate_iss_map.Rd
  man/generate_npafp_maps.Rd
  man/generate_npafp_maps_dist.Rd
  man/generate_pop_map.Rd
  man/generate_stool_ad_maps.Rd
  man/generate_stool_ad_maps_dist.Rd
  man/generate_timeliness_maps.Rd
Labels: enhancement, High Priority
