Repository CDCgov/sirfunctions, pull requests merged in 2024-01, with the labels that each got.

#19 16 - Raw.data - metadata - object
  R/dal.R
Labels: enhancement

#18 17 - CrUD EDAV functionality
  R/dal.R
Labels: enhancement

#21 #18 update edav_ios
  R/dal.R
Labels: bug

#30 closes #28 #27
  README.md
Labels: documentation, enhancement

#34 :bug: fixed edav_io token specification closes #33
  R/dal.R
Labels: bug

#37 29 add metadata tags to figures and tables
  R/f.metadata.tag.R
Labels: enhancement
