Repository CDCgov/sirfunctions, pull requests merged in 2024-08, with the labels that each got.

#114 ❇️ caption sizes for NPAFP and Stool Adequacy Maps 🐛 ISS data loading logic
  R/dr.figure.functions.R
  R/dr.main.functions.R
  man/generate_dist_pop_map.Rd
  man/generate_npafp_maps.Rd
  man/generate_npafp_maps_dist.Rd
  man/generate_pop_map.Rd
  man/generate_stool_ad_maps.Rd
  man/generate_stool_ad_maps_dist.Rd
Labels: bug, enhancement

#115 🐛 `f.metadata.tag()` not using `raw.data` when time_tag param is NA
  R/f.metadata.tag.R
  man/f.metadata.tag.Rd
  tests/testthat/test-f.metadata.tag.R
Labels: bug

#116 ❇️ Compress plot images function
  R/dal.R
Labels: enhancement

#119 making assignment of corrupted.rds explicit outside of trycatch
  R/dal.R
Labels: bug

#124 123 add additional afp duplicate checking in get all polio data
  NAMESPACE
  R/dal.R
  man/compress_png.Rd
Labels: enhancement
