Repository CDCgov/sirfunctions, pull requests merged in 2025-06, with the labels that each got.

#316 sirfunctions 1.3.5
  .DS_Store
  DESCRIPTION
  R/dal.R
  man/create_polis_data_folder.Rd
  man/get_all_polio_data.Rd
Labels: bug, enhancement

#324 ❇️ Vignette to run the kpi analysis
  vignettes/kpi-analysis.Rmd
Labels: documentation

#317 ❇️ 315 make archiving optional in get_all_polio_data
  .gitignore
  R/dal.R
  man/create_polis_data_folder.Rd
  man/edav_io.Rd
  man/get_all_polio_data.Rd
Labels: enhancement

#294 All recreation of old `polio_data` from archived Core Ready polis files
  R/dal.R
  man/get_all_polio_data.Rd
  man/get_archived_polis_data.Rd
Labels: enhancement

#310 ❇️ Add ability to read and write parquet files from edav io
  DESCRIPTION
  R/dal.R
  R/sirfunctions-package.R
Labels: enhancement

#329 ❇️ Add ability to set KPI targets
  R/kpi.figure.functions.R
  R/kpi.table.functions.R
  man/export_kpi_table.Rd
  man/generate_c1_rollup.Rd
  man/generate_c3_rollup.Rd
Labels: enhancement

#327 🐛 Fix lab interval calculations and the adhoc map
  R/dr.afp.functions.R
  R/dr.excel.export.functions.R
  R/dr.figure.functions.R
  R/dr.lab.functions.R
  R/generate_adhoc_map.R
  man/generate_lab_timeliness.Rd
Labels: bug
