Repository CDCgov/sirfunctions, pull requests merged in 2025-07, with the labels that each got.

#343 ❇️ Process and extract IHME coverage data to SIR spatial resources
  DESCRIPTION
  NAMESPACE
  R/update_vacc_cov_data.R
  man/update_vacc_cov_data.Rd
Labels: documentation, enhancement

#335 ❇️ Create emergence maps showing case count
  NAMESPACE
  R/dr.figure.functions.R
  R/generate_incidence_map.R
  man/generate_incidence_map.Rd
  renv.lock
Labels: enhancement

#342 sirfunctions patch v2.0.1
  DESCRIPTION
  R/dal.R
Labels: bug
